#ifndef AREUMII_CONFIG_H
#define AREUMII_CONFIG_H

#define SHM_INDEX_LEFT_SHOULDER_ROLL     0
#define SHM_INDEX_LEFT_SHOULDER_PITCH    1
#define SHM_INDEX_LEFT_SHOULDER_YAW      2 
#define SHM_INDEX_LEFT_ELBOW_PITCH       3
#define SHM_INDEX_LEFT_WRIST_ROLL        4
#define SHM_INDEX_LEFT_WRIST_YAW         5 
#define SHM_INDEX_LEFT_WRIST_PITCH       6
#define SHM_INDEX_LEFT_GRIPPER           7

#define SHM_INDEX_RIGHT_SHOULDER_ROLL    8
#define SHM_INDEX_RIGHT_SHOULDER_PITCH   9
#define SHM_INDEX_RIGHT_SHOULDER_YAW     10
#define SHM_INDEX_RIGHT_ELBOW_PITCH      11
#define SHM_INDEX_RIGHT_WRIST_ROLL       12
#define SHM_INDEX_RIGHT_WRIST_YAW        13
#define SHM_INDEX_RIGHT_WRIST_PITCH      14
#define SHM_INDEX_RIGHT_GRIPPER          15



#define CONTROL_VEC_INDEX_LEFT_SHOULDER_ROLL     0
#define CONTROL_VEC_INDEX_LEFT_SHOULDER_PITCH    1
#define CONTROL_VEC_INDEX_LEFT_SHOULDER_YAW      2 
#define CONTROL_VEC_INDEX_LEFT_ELBOW_PITCH       3
#define CONTROL_VEC_INDEX_LEFT_WRIST_ROLL        4
#define CONTROL_VEC_INDEX_LEFT_WRIST_YAW         5 
#define CONTROL_VEC_INDEX_LEFT_WRIST_PITCH       6
#define CONTROL_VEC_INDEX_LEFT_GRIPPER           7

#define CONTROL_VEC_INDEX_RIGHT_SHOULDER_ROLL    8
#define CONTROL_VEC_INDEX_RIGHT_SHOULDER_PITCH   9
#define CONTROL_VEC_INDEX_RIGHT_SHOULDER_YAW     10
#define CONTROL_VEC_INDEX_RIGHT_ELBOW_PITCH      11
#define CONTROL_VEC_INDEX_RIGHT_WRIST_ROLL       12
#define CONTROL_VEC_INDEX_RIGHT_WRIST_YAW        13
#define CONTROL_VEC_INDEX_RIGHT_WRIST_PITCH      14
#define CONTROL_VEC_INDEX_RIGHT_GRIPPER          15

#endif